# Práctica Clase 2

1) Abrir el archivo "Emisiones_CO2.csv" y cargar sus datos en un diccionario.

In [3]:
import os
archivo = open('Emisiones_CO2.csv',encoding='latin-1')

In [4]:
dicc_emisiones = {  'cod_pais' : [],
                    'nom_pais' : [],
                    'region' : [],
                    'anio' : [],
                    'co2' : [],
                    'co2_percapita' : []}

2) a) ¿Cuántas variables hay? <br>
b) ¿Qué tipos de datos usar para cada una? <br>
c) ¿Qué tipo de variables son? <br>
d) ¿Hay valores faltantes? <br>
e) ¿Cuál es el total de emisiones de CO2 para 'América Latina y Caribe' en el año 2010?

In [5]:
for i in range(5):
    line = archivo.readline()
    print(line)

# Close the file
archivo.close()

Código de país|Nombre del país|Región|Año|CO2 (kt)|CO2 per cápita (toneladas métricas)

ABW|Aruba|América Latina y Caribe|1960||

ABW|Aruba|América Latina y Caribe|1961||

ABW|Aruba|América Latina y Caribe|1962||

ABW|Aruba|América Latina y Caribe|1963||

In [6]:
import pandas as pd

df_emisiones = pd.read_csv('Emisiones_CO2.csv', encoding='latin-1', sep="|")

In [7]:
df_emisiones.head(10)

,Código de país,Nombre del país,Región,Año,CO2 (kt),CO2 per cápita (toneladas métricas)
0,ABW,Aruba,América Latina y Caribe,1960,NaN,NaN
1,ABW,Aruba,América Latina y Caribe,1961,NaN,NaN
2,ABW,Aruba,América Latina y Caribe,1962,NaN,NaN
3,ABW,Aruba,América Latina y Caribe,1963,NaN,NaN
4,ABW,Aruba,América Latina y Caribe,1964,NaN,NaN
5,ABW,Aruba,América Latina y Caribe,1965,NaN,NaN
6,ABW,Aruba,América Latina y Caribe,1966,NaN,NaN
7,ABW,Aruba,América Latina y Caribe,1967,NaN,NaN
8,ABW,Aruba,América Latina y Caribe,1968,NaN,NaN
9,ABW,Aruba,América Latina y Caribe,1969,NaN,NaN

In [8]:
df_emisiones2 = df_emisiones.dropna(axis=0, inplace=False)
df_emisiones3 = df_emisiones.dropna(axis=1, inplace=False)

In [9]:
df_emisiones2

,Código de país,Nombre del país,Región,Año,CO2 (kt),CO2 per cápita (toneladas métricas)
26,ABW,Aruba,América Latina y Caribe,1986,"179,683","2,868319392"
27,ABW,Aruba,América Latina y Caribe,1987,"447,374","7,234964017"
28,ABW,Aruba,América Latina y Caribe,1988,"612,389","10,026507523"
29,ABW,Aruba,América Latina y Caribe,1989,"649,059","10,634732599"
30,ABW,Aruba,América Latina y Caribe,1990,"1.840,83","29,620164768"
...,...,...,...,...,...,...
11122,ZWE,Zimbabue,África subsahariana,2007,"9.732,22","0,731866885"
11123,ZWE,Zimbabue,África subsahariana,2008,"7.682,37","0,569255428"
11124,ZWE,Zimbabue,África subsahariana,2009,"8.239,75","0,600521157"
11125,ZWE,Zimbabue,África subsahariana,2010,"9.028,15","0,646072745"
11126,ZWE,Zimbabue,África subsahariana,2011,"9.860,56","0,691697897"

In [10]:
df_emisiones3

      Código de país Nombre del país                   Región   Año
0                ABW           Aruba  América Latina y Caribe  1960
1                ABW           Aruba  América Latina y Caribe  1961
2                ABW           Aruba  América Latina y Caribe  1962
3                ABW           Aruba  América Latina y Caribe  1963
4                ABW           Aruba  América Latina y Caribe  1964
...              ...             ...                      ...   ...
11122            ZWE        Zimbabue      África subsahariana  2007
11123            ZWE        Zimbabue      África subsahariana  2008
11124            ZWE        Zimbabue      África subsahariana  2009
11125            ZWE        Zimbabue      África subsahariana  2010
11126            ZWE        Zimbabue      África subsahariana  2011

[11127 rows x 4 columns]

In [11]:
df_emisiones2.info

<bound method DataFrame.info of       Código de país Nombre del país                   Región   Año  CO2 (kt)  \
26               ABW           Aruba  América Latina y Caribe  1986   179,683
27               ABW           Aruba  América Latina y Caribe  1987   447,374
28               ABW           Aruba  América Latina y Caribe  1988   612,389
29               ABW           Aruba  América Latina y Caribe  1989   649,059
30               ABW           Aruba  América Latina y Caribe  1990  1.840,83
...              ...             ...                      ...   ...       ...
11122            ZWE        Zimbabue      África subsahariana  2007  9.732,22
11123            ZWE        Zimbabue      África subsahariana  2008  7.682,37
11124            ZWE        Zimbabue      África subsahariana  2009  8.239,75
11125            ZWE        Zimbabue      África subsahariana  2010  9.028,15
11126            ZWE        Zimbabue      África subsahariana  2011  9.860,56

      CO2 per cápita (toneladas métricas)
26                            2,868319392
27                            7,234964017
28                           10,026507523
29                           10,634732599
30                           29,620164768
...                                   ...
11122                         0,731866885
11123                         0,569255428
11124                         0,600521157
11125                         0,646072745
11126                         0,691697897

[9029 rows x 6 columns]>

In [12]:
df_emisiones.columns

Index(['Código de país', 'Nombre del país', 'Región', 'Año', 'CO2 (kt)',
       'CO2 per cápita (toneladas métricas)'],
      dtype='object')

In [13]:
for columna in (df_emisiones.columns):
    
    dicc_emisiones['cod_pais' ].append(columna)
    dicc_emisiones['nom_pais' ].append(columna)
    dicc_emisiones['region' ].append(columna)
    dicc_emisiones['anio' ].append(columna)
    dicc_emisiones['co2' ].append(columna)
    dicc_emisiones['co2_percapita'].append(columna)

In [14]:
dicc_emisiones

{'cod_pais': ['Código de país',
  'Nombre del país',
  'Región',
  'Año',
  'CO2 (kt)',
  'CO2 per cápita (toneladas métricas)'],
 'nom_pais': ['Código de país',
  'Nombre del país',
  'Región',
  'Año',
  'CO2 (kt)',
  'CO2 per cápita (toneladas métricas)'],
 'region': ['Código de país',
  'Nombre del país',
  'Región',
  'Año',
  'CO2 (kt)',
  'CO2 per cápita (toneladas métricas)'],
 'anio': ['Código de país',
  'Nombre del país',
  'Región',
  'Año',
  'CO2 (kt)',
  'CO2 per cápita (toneladas métricas)'],
 'co2': ['Código de país',
  'Nombre del país',
  'Región',
  'Año',
  'CO2 (kt)',
  'CO2 per cápita (toneladas métricas)'],
 'co2_percapita': ['Código de país',
  'Nombre del país',
  'Región',
  'Año',
  'CO2 (kt)',
  'CO2 per cápita (toneladas métricas)']}

In [16]:
df_emisiones.sort_index(inplace=True)

In [ ]:
df_emisiones.concat()